name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - requests=2.24.0
  - pip:
      - scipy==1.15.1 
      - scikit-learn==1.6.1
      - mlflow==3.3.2
      - wandb==0.21.3
      - -e ..