name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - requests=2.24.0
  - pip:
      - pandas==2.3.2
      - scikit-learn==1.7.2
      - mlflow==3.3.2
      - wandb==0.21.3
      - -e ..
