name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
      - hydra-core==1.3.2
      - matplotlib==3.10.7
      - pandas==2.3.2
      - scipy==1.15.1 
      - scikit-learn==1.7.2
